#!/bin/bash
set -e

mysql --protocol=socket -uroot -p$MYSQL_ROOT_PASSWORD <<EOSQL
CREATE USER '$MYSQL_USERNAME_1'@'%' IDENTIFIED BY '$MYSQL_USERPASS_1';
GRANT SELECT ON $MYSQL_DATABASE.* TO '$MYSQL_USERNAME_1'@'%';

CREATE USER '$MYSQL_USERNAME_2'@'%' IDENTIFIED BY '$MYSQL_USERPASS_2';
GRANT INSERT, UPDATE, SELECT, DELETE ON $MYSQL_DATABASE.* TO '$MYSQL_USERNAME_2'@'%';
EOSQL
